//! Embed the SPA bundle (`ui/dist`) into the csl-service wasm so the service can
//! stage the default environment into `/data/static` on first boot — EXCEPT
//! videos and large media (the 26 MB background video and its ~14 MB poster),
//! which would bloat the component. Emits `EMBEDDED_STATIC: &[(rel, bytes)]`.
//!
//! If `ui/dist` is absent (UI not built), the table is empty — the service still
//! runs, it just won't stage the SPA.
use std::{env, fs, path::{Path, PathBuf}};

const MAX_EMBED_BYTES: u64 = 2_000_000; // skip large media (poster, etc.)
const VIDEO_EXTS: &[&str] = &["mp4", "webm", "mov", "m4v"];

fn main() {
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let dist = manifest.join("../../ui/dist");
    println!("cargo:rerun-if-changed={}", dist.display());

    let mut files: Vec<(String, String)> = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut files);
    } else {
        println!("cargo:warning=csl-service: ui/dist not found ({}); SPA will not be embedded", dist.display());
    }

    let mut code = String::from("// @generated by build.rs\npub static EMBEDDED_STATIC: &[(&str, &[u8])] = &[\n");
    for (rel, abs) in &files {
        code.push_str(&format!("    ({rel:?}, include_bytes!({abs:?})),\n"));
    }
    code.push_str("];\n");
    fs::write(out.join("embedded_static.rs"), code).unwrap();
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for entry in rd.flatten() {
        let p = entry.path();
        let rel = p.strip_prefix(root).unwrap().to_string_lossy().replace('\\', "/");
        if p.is_dir() {
            if rel == "video" { continue; } // EXCEPT videos
            collect(root, &p, out);
            continue;
        }
        let is_video = p.extension().and_then(|e| e.to_str()).map(|e| VIDEO_EXTS.contains(&e)).unwrap_or(false);
        let too_big = entry.metadata().map(|m| m.len() > MAX_EMBED_BYTES).unwrap_or(false);
        if is_video || too_big {
            println!("cargo:warning=csl-service: skipping embed of {rel} (video/large media)");
            continue;
        }
        out.push((rel, p.to_string_lossy().into_owned()));
    }
}
